media_folder: "public/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media" # The src attribute for uploaded media will begin with /images/uploads

publish_mode: editorial_workflow

backend:
  name: github
  repo: dojo4/dojo4.com
  branch: master # Branch to update (optional; defaults to master)


collections:
  - name: "posts"
    label: "Post"
    folder: "data/posts"
    create: true
    filter:
      field: _type
      value: post
    fields:
      - {label: "Type", name: "_type", default: "post"}

