#
  backend:
    name: git-gateway
    #name: git
    branch: master

  publish_mode: editorial_workflow

  media_folder: "public/media"
  public_folder: "../media"

#
  title_field: &title_field
    label: "Title"
    name: title
    widget: string
    required: true

  name_field: &name_field
    label: "Name"
    name: name
    widget: string
    required: true

  body_field: &body_field
    label: "Body"
    name: body
    widget: markdown
    default: "- this\n- is\n- _markdown_\n\n\nref: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet"

  published_at_field: &published_at_field
    label: "Published At"
    name: published_at 
    widget: datetime

  og_field: &og_field
    label: "Open Graph"
    name: og
    widget: object
    required: false
    fields:
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}

#
  collections:
    - name: "posts"
      label: "Posts"
      label_singular: "Post"
      folder: "data/posts"
      create: true
      slug: "{{slug}}"
      format: yaml-frontmatter
      fields:
        -
          <<: *title_field
        -
          label: "Author"
          name: author
          widget: relation
          collection: people
          searchFields: ["title", "email"]
          valueField: email
          
        -
          <<: *body_field
        -
          <<: *published_at_field
        -
          <<: *og_field

    - name: "people"
      label: "People"
      label_singular: "Person"
      folder: "data/people"
      create: true
      slug: "{{slug}}"
      format: yaml-frontmatter
      fields:
        -
          <<: *title_field
        -
          label: "Email"
          name: email
          widget: string
        -
          <<: *body_field
        -
          <<: *published_at_field
        -
          <<: *og_field
